import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Core tokens
        bg:        "#0A0A0F",
        surface:   "#111118",
        elevated:  "#1A1A24",
        border:    "#2A2A38",
        hex:       "#00FF88",
        "hex-dim": "rgba(0,255,136,0.08)",
        text: {
          primary:   "#F0F0F8",
          secondary: "#8888A8",
          muted:     "#44445A",
          code:      "#A8FFB8",
        },
        red:    "#FF4455",
        yellow: "#FFB700",
        blue:   "#4488FF",
        // Stitch design system color names
        "primary-container":        "#00ff88",
        "on-primary-container":     "#007139",
        "on-primary":               "#003919",
        "on-primary-fixed":         "#00210c",
        "primary-fixed":            "#60ff99",
        "primary-fixed-dim":        "#00e479",
        "secondary":                "#3fe882",
        "secondary-container":      "#00cb69",
        "on-secondary":             "#003919",
        "on-secondary-container":   "#004f25",
        "secondary-fixed":          "#61ff98",
        "secondary-fixed-dim":      "#37e27d",
        "accent-dim":               "rgba(0, 255, 136, 0.08)",
        "border-subtle":            "#2A2A38",
        "surface-elevated":         "#1A1A24",
        "surface-container":        "#1f1f25",
        "surface-container-high":   "#2a292f",
        "surface-container-highest":"#35343a",
        "surface-container-low":    "#1b1b20",
        "surface-container-lowest": "#0e0e13",
        "surface-dim":              "#131318",
        "surface-bright":           "#39383e",
        "surface-variant":          "#35343a",
        "surface-tint":             "#00e479",
        "on-surface":               "#e4e1e9",
        "on-surface-variant":       "#b9cbb9",
        "outline":                  "#849585",
        "outline-variant":          "#3b4b3d",
        "inverse-surface":          "#e4e1e9",
        "inverse-on-surface":       "#303036",
        "inverse-primary":          "#006d37",
        "background":               "#0A0A0F",
        "on-background":            "#e4e1e9",
        "text-primary":             "#F0F0F8",
        "text-secondary":           "#8888A8",
        "code-highlight":           "#A8FFB8",
        "tertiary":                 "#fffaf7",
        "tertiary-container":       "#ffdb79",
        "on-tertiary":              "#3d2f00",
        "on-tertiary-container":    "#795f01",
        "tertiary-fixed":           "#ffe08d",
        "tertiary-fixed-dim":       "#e5c364",
        "on-tertiary-fixed":        "#241a00",
        "on-tertiary-fixed-variant":"#584400",
        "error":                    "#ffb4ab",
        "error-container":          "#93000a",
        "on-error":                 "#690005",
        "on-error-container":       "#ffdad6",
      },
      fontFamily: {
        sans:         ["var(--font-geist-sans)", "Inter", "system-ui", "sans-serif"],
        mono:         ["var(--font-geist-mono)", "JetBrains Mono", "monospace"],
        "code-block": ["var(--font-geist-mono)", "JetBrains Mono", "monospace"],
        "label-caps": ["var(--font-geist-mono)", "JetBrains Mono", "monospace"],
        "display-lg": ["var(--font-geist-sans)", "Inter", "system-ui", "sans-serif"],
        "headline-md":["var(--font-geist-sans)", "Inter", "system-ui", "sans-serif"],
        "headline-sm":["var(--font-geist-sans)", "Inter", "system-ui", "sans-serif"],
        "body-md":    ["Inter", "system-ui", "sans-serif"],
        "body-lg":    ["Inter", "system-ui", "sans-serif"],
      },
      fontSize: {
        "label-caps":  ["12px",  { lineHeight: "1",   letterSpacing: "0.05em",  fontWeight: "600" }],
        "body-md":     ["16px",  { lineHeight: "1.5", letterSpacing: "0",       fontWeight: "400" }],
        "body-lg":     ["18px",  { lineHeight: "1.6", letterSpacing: "0",       fontWeight: "400" }],
        "code-block":  ["14px",  { lineHeight: "1.7", letterSpacing: "0",       fontWeight: "400" }],
        "headline-sm": ["24px",  { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["32px",  { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        "display-lg":  ["48px",  { lineHeight: "1.1", letterSpacing: "-0.03em", fontWeight: "700" }],
      },
      spacing: {
        "base":             "4px",
        "stack-sm":         "8px",
        "stack-md":         "16px",
        "stack-lg":         "32px",
        "gutter":           "16px",
        "container-margin": "24px",
      },
      backgroundImage: {
        "grid-faint": `linear-gradient(rgba(255,255,255,0.015) 1px, transparent 1px),
                       linear-gradient(90deg, rgba(255,255,255,0.015) 1px, transparent 1px)`,
      },
      backgroundSize: {
        grid:     "40px 40px",
        "grid-24":"24px 24px",
      },
      boxShadow: {
        "hex-glow":    "0 0 20px rgba(0,255,136,0.08)",
        "hex-glow-md": "0 0 40px rgba(0,255,136,0.12)",
        "glow-sm":     "0 0 12px rgba(0,255,136,0.2)",
        "glow-card":   "0 4px 12px rgba(0,255,136,0.05)",
      },
      animation: {
        "fade-up":  "fadeUp 0.5s ease forwards",
        "blink":    "blink 1s step-end infinite",
        "fadeIn-35":"fadeIn 0.5s ease-out 3.5s forwards",
        "fadeIn-45":"fadeIn 0.5s ease-out 4.5s forwards",
        "fadeIn-5": "fadeIn 0.5s ease-out 5s forwards",
      },
      keyframes: {
        fadeUp: {
          "0%":   { opacity: "0", transform: "translateY(12px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        blink: {
          "0%, 100%": { opacity: "1" },
          "50%":      { opacity: "0" },
        },
        fadeIn: {
          to: { opacity: "1" },
        },
      },
    },
  },
  plugins: [],
};

export default config;
